server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # 路由id，可以任意
        - id: user-service-route
          # 代理的服务地址
          uri: http://127.0.0.1:8093
          # 路由断言： 可以匹配映射路径
          predicates:
            - Path=/user/**
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8089/eureka
  instance:
    prefer-ip-address: true